export const PHASES = {
  IDLE: "IDLE",
  PHASE_1_INGESTION: "PHASE_1_INGESTION",
  TRANSITION_CUT: "TRANSITION_CUT",
  PHASE_2_COGNITIVE: "PHASE_2_COGNITIVE",
  PHASE_3_SYNTHESIS: "PHASE_3_SYNTHESIS",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
} as const;

export const TIMING = {
  STAGGER_DELAY: 0.15,
  CUT_HOLD_MS: 200,
  CUT_FADE_DURATION: 0.1,
  SLAM_DURATION: 0.3,
  SIDEBAR_SLIDE_DURATION: 0.4,
  SCANNER_LOOP_DURATION_S: 1.5,
} as const;

export const IS_VISUAL_TEST_MODE =
  process.env.NEXT_PUBLIC_VISUAL_TEST_MODE === "1";

export const SLOT_LABELS = [
  "F R A M E _ 0 1",
  "F R A M E _ 0 2",
  "F R A M E _ 0 3",
  "A U D I O",
] as const;
